---
title: "Final Project Write Up"
author: "Micah Slaughter, Jonathan Kacvinsky"
date: "4 March 2025"
format:
  html: default
  pdf:
    fontsize: 10pt
    include-in-header:
      text: |
        \usepackage[margin=0.75in]{geometry}
        \usepackage{setspace}
        \setstretch{0.95}
        \makeatletter
        \renewcommand{\maketitle}{
          \begin{center}
            {\LARGE \bfseries \@title \par}
            \vspace{0.2em} 
            {\normalsize \@author \par}
            \vspace{0.2em} 
            {\small \@date \par}
          \end{center}
          \vspace{-1em} 
        }
        \makeatother
output:
  echo: false
  eval: false
execute: 
  echo: false
execute-dir: project
---
Micah Slaughter (micslaugh) and Jonathan Kacvinsky (kacvinsky11), section 2 - Monday/Wednesday 10:30-11:50

## Do Illinois counties with higher carbon emissions show worse health outcomes?

This project is an exploratory examination of scope 1 and 2 carbon emissions on health outcomes across counties in Illinois. In 2025, the state of Illinois passed the Corporate Climate Accountability Act, which mandates more stringent tracking and reporting of carbon emissions. The bill establishes reporting standards for scope 1, 2, and 3 carbon emissions, which capture a more holistic measurement of pollution than previously required. In this data project, we aim to establish a baseline understanding of health status in Illinois under current scope 1 and 2 emissions levels to better measure the impact that increased carbon emissions reporting and regulation may have on statewide health outcomes. The data used capture both directly reported carbon emissions and air quality index data. Statewide health outcomes are reflected through cancer, asthma, and chronic obstructive pulmonary disease (COPD) incidence as well as severe complications for Covid-19, heart failure, and stroke. To more closely examine the relationship between carbon emissions and cancer incidence, the cancer data is constructed to include the 5 types of cancer shown to have the greatest linkage to pollutants and environmental factors. These types include bladder, breast, kidney, colorectal, and lung and bronchus cancers. For each health outcome category, there are data limitations to reporting both for the years of available data and for data privacy concerns to de-identify individuals. 

```{python}
import geopandas as gpd
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import shapely
from shapely import wkt
import numpy as np
import altair as alt 
import streamlit as st
from matplotlib.ticker import ScalarFormatter
import matplotlib.colors as mcolors
import matplotlib.colorbar as mcolorbar

import warnings 
warnings.filterwarnings('ignore')
alt.renderers.enable("png")
alt.data_transformers.disable_max_rows()

# improve graph resolution
import tempfile 
from IPython.display import SVG, display, Image
import vl_convert as vlc

def display_altair_png(chart, scale=2):
    """
    Render an Altair chart to a PNG and display it inline.

    Parameters
    ----------
    chart : altair.Chart
        Altair chart object to render.
    scale : int, optional
        Resolution scaling factor for the PNG (default = 2). Use scale=2 for standard slides. Use scale = 3–4 for dense figures or PDF exports.
    """
    png_bytes = vlc.vegalite_to_png(chart.to_dict(), scale=scale)

    # Write to a temporary PNG file and display
    with tempfile.NamedTemporaryFile(suffix=".png") as tmp:
        tmp.write(png_bytes)
        tmp.flush()
        display(Image(filename=tmp.name))

script_dir = Path.cwd()
# data_path = base_dir / "data" / "file.csv"
# script_dir = Path(__file__).parent

#Preprocessing script

# Creating single file of emissions related cancers by county for 2016-2020  
files = [
    "lung-bronch_cancer",
    "breast_cancer",
    "colorectal_cancer",
    "kidney_cancer",
    "bladder_cancer"]

cancer_df = pd.DataFrame()

for file in files:
    raw_cancer = script_dir / f"data/raw-data/{file}.csv"
    output_cancer = script_dir / f"data/derived-data/{file}_filtered.csv"
    
    df = pd.read_csv(raw_cancer)

    cancer_col = df.columns[6]

    df = df[["CountyFIPS", "County", cancer_col]]
    df = df.rename(columns={cancer_col: file})
    
    if cancer_df.empty:
        cancer_df = df
    else:
        cancer_df = pd.merge(cancer_df, df, on=["CountyFIPS", "County"], how="outer")

# Preparing cancer file for plotting
columns = [
    'lung-bronch_cancer',
    'breast_cancer',
    'colorectal_cancer',
    'kidney_cancer',
    'bladder_cancer']

# Replace "Suppressed" with NaN for blank county values
cancer_df[columns] = cancer_df[columns].replace("Suppressed", np.nan)
cancer_df[columns] = cancer_df[columns].apply(pd.to_numeric, errors='coerce')

# Reshape to tidy dataset
cancer_df = cancer_df.melt(
    id_vars=['CountyFIPS', 'County'],
    value_vars=columns,
    var_name='Cancer Type',
    value_name='Incidence')

final_output = script_dir / "data/derived-data/combined_cancer_by_county.csv"

cancer_df.to_csv(final_output, index=False) 

# Cleaning crude prevalence of COPD by county
raw_copd = script_dir / 'data/raw-data/crude_COPD.csv'
output_copd = script_dir / 'data/derived-data/COPD_filtered.csv'

copd_df = pd.read_csv(raw_copd)

copd_filtered = copd_df[["CountyFIPS", "County", "Year", "Value"]]

copd_filtered.to_csv(output_copd, index=False)

# Cleaning crude prevalance of asthma by county
raw_asthma = script_dir / 'data/raw-data/crude_asthma.csv'
output_asthma = script_dir / 'data/derived-data/asthma_filtered.csv'

asthma_df = pd.read_csv(raw_asthma)

asthma_filtered = asthma_df[["CountyFIPS", "County", "Year", "Value"]]

asthma_filtered.to_csv(output_asthma, index=False)

# Loading carbon emissions file

raw_ghgp = script_dir / 'data/raw-data/ghgp_data_2021.xlsx'
output_ghgp = script_dir / 'data/derived-data/ghgp.csv'

# Cleaning carbon emissions

ghgp = pd.read_excel(raw_ghgp)

ghgp = ghgp.iloc[3:].reset_index(drop=True)

ghgp = ghgp[["Unnamed: 4", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Unnamed: 13"]]
ghgp.rename(columns={"Unnamed: 4": "State", "Unnamed: 7": "County", "Unnamed: 8": "Latitude", "Unnamed: 9": "Longitude", "Unnamed: 13": "Total Direct Emissions"}, inplace=True)

ghgp = ghgp[ghgp["State"] == "IL"]
ghgp = ghgp.dropna()

ghgp["County"] = (ghgp["County"]
                  .astype(str)
                  .str.strip()
                  .str.lower()
                  .str.replace(r"county.*$", "", regex=True)
                  .str.replace(r"\s+", " ", regex=True)
                  .str.strip()
                  .str.title()
)

ghgp = ghgp.groupby("County", as_index=False).agg({
    "Total Direct Emissions": "sum",
    "Latitude": "mean",
    "Longitude": "mean"
})

ghgp = ghgp[ghgp["County"] != "Lasalle"]

ghgp.to_csv(output_ghgp, index=False)

# Loading AQI file

raw_aqi = script_dir / 'data/raw-data/daily_aqi_by_county_2025.csv'
output_aqi = script_dir / 'data/derived-data/aqi.csv'

# Cleaning AQI file

aqi = pd.read_csv(raw_aqi)

aqi = aqi[["State Name", "county Name", "AQI", "Defining Parameter"]]
aqi.rename(columns={"State Name": "State", "county Name": "County"}, inplace=True)

aqi = aqi[aqi["State"] == "Illinois"]

aqi = aqi.groupby(["County", "Defining Parameter"], as_index=False).agg({"AQI": "mean"})

aqi.to_csv(output_aqi, index=False)

# Loading Stroke file

raw_stroke = script_dir / 'data/raw-data/heart_stroke_mortality.csv'
output_stroke = script_dir / 'data/derived-data/stroke.csv'

# Cleaning Stroke file

stroke = pd.read_csv(raw_stroke)

stroke = stroke[stroke["Year"] == "2019"]
stroke = stroke[stroke["Topic"] == "All stroke"]

stroke = stroke[["Year", "LocationAbbr", "LocationDesc", "Topic", "Data_Value"]]
stroke.rename(columns={"LocationAbbr": "State", "LocationDesc": "County"}, inplace=True)

stroke = stroke.dropna()
stroke = stroke.groupby("County", as_index=False).agg({"Data_Value": "sum"})

stroke.to_csv(output_stroke, index=False)

# Loading Heart file

raw_heart = script_dir / 'data/raw-data/heart_stroke_mortality.csv'
output_heart = script_dir / 'data/derived-data/heart.csv'

# Cleaning Heart file

heart = pd.read_csv(raw_heart)

heart = heart[heart["Year"] == "2019"]
heart = heart[heart["Topic"] == "All heart disease"]

heart = heart[["Year", "LocationAbbr", "LocationDesc", "Topic", "Data_Value"]]
heart.rename(columns={"LocationAbbr": "State", "LocationDesc": "County"}, inplace=True)

heart = heart.dropna()
heart = heart.groupby("County", as_index=False).agg({"Data_Value": "sum"})

heart.to_csv(output_heart, index=False)

# Loading COVID file

raw_covid = script_dir / 'data/raw-data/us-counties.csv'
output_covid = script_dir / 'data/derived-data/covid.csv'

# Cleaning COVID file

cov = pd.read_csv(raw_covid)

cov["Date"] = 2020

cov = cov[["Date", "County", "State", "Deaths"]]

cov = cov.groupby("County", as_index=False).agg({"Deaths": "sum"})

cov.to_csv(output_covid, index=False)

# Loading Population file

raw_pop = script_dir / 'data/raw-data/population_illinois.xlsx'
output_pop = script_dir / 'data/derived-data/population.csv'

#Illinois Population by County

pop = pd.read_excel(raw_pop)

pop["County"] = (pop["County"]
                  .astype(str)
                  .str.strip()
                  .str.lower()
                  .str.replace(r"county.*$", "", regex=True)
                  .str.replace(r"\s+", " ", regex=True)
                  .str.replace(".", "")
                  .str.strip()
                  .str.title()
)

pop.to_csv(output_pop, index=False)

output_outcomes = script_dir / 'data/derived-data/outcomes.csv'

ghgp_20 = ghgp.sort_values(by="Total Direct Emissions", ascending=False).head(20).reset_index().copy()
top_20 = ghgp_20["County"].unique()
asthma_20 = asthma_filtered[asthma_filtered["County"].isin(top_20)].copy()
copd_20 = copd_filtered[copd_filtered["County"].isin(top_20)].copy()
covid_20 = cov[cov["County"].isin(top_20)].copy()
heart_20 = heart[heart["County"].isin(top_20)].copy()
stroke_20 = stroke[stroke["County"].isin(top_20)].copy()
pop_20 = pop[pop["County"].isin(top_20)].copy()
"""Ranked carbon emissions by top 20 counties with highest direct emissions"""
"""Subsetted every dataset to top 20"""

asthma_20 = asthma_20.rename(columns={"Value": "Asthma Incidence"})
copd_20 = copd_20.rename(columns={"Value": "COPD Deaths"})
covid_20 = covid_20.rename(columns={"Deaths": "COVID Deaths"})
heart_20 = heart_20.rename(columns={"Data_Value": "Heart Failures"})
stroke_20 = stroke_20.rename(columns={"Data_Value": "Stroke Deaths"})

ghgp_20 = ghgp_20[["County", "Total Direct Emissions"]]
asthma_20 = asthma_20[["County", "Asthma Incidence"]]
copd_20 = copd_20[["County", "COPD Deaths"]]
"""Standardizing for merge"""

outcomes = ghgp_20.copy()

outcomes = outcomes.merge(asthma_20, on="County", how="left")
outcomes = outcomes.merge(copd_20, on="County", how="left")
outcomes = outcomes.merge(covid_20, on="County", how="left")
outcomes = outcomes.merge(heart_20, on="County", how="left")
outcomes = outcomes.merge(stroke_20, on="County", how="left")
outcomes = outcomes.merge(pop_20, on="County", how="left")

outcomes["Asthma Incidence"] = outcomes["Asthma Incidence"]
outcomes["COPD Deaths"] = outcomes["COPD Deaths"]
"""Removing % signs"""


outcomes["COVID Deaths"] = outcomes["COVID Deaths"].astype(float)
outcomes["Heart Failures"] = outcomes["Heart Failures"].astype(float)
outcomes["Stroke Deaths"] = outcomes["Stroke Deaths"].astype(float)
outcomes["Population"] = outcomes["Population"].astype(float)
"""Standardizing dtype"""

outcomes["COVID Deaths"] = round((outcomes["COVID Deaths"]/outcomes["Population"]) * 100, 2)
outcomes["Heart Failures"] = round((outcomes["Heart Failures"]/outcomes["Population"]) * 100, 2)
outcomes["Stroke Deaths"] = round((outcomes["Stroke Deaths"]/outcomes["Population"]) * 100, 2)
"""Turning rest into percents"""

outcomes["Asthma Incidence"] = outcomes["Asthma Incidence"].str.replace("%", "")
outcomes["COPD Deaths"] = outcomes["COPD Deaths"].str.replace("%", "")
"""Removing % to standardize"""
                          
outcomes.to_csv(output_outcomes, index=False)
```

This graph is structured so that the 20 counties with the highest carbon emissions in Illinois are denoted from left to right, with the left representing the county with the highest emissions. Asthma incidence, COPD deaths, COVID deaths, heart failures, and stroke deaths are converted to percentage per county population to standardize variables. Each health outcome is depicted as a bar graph so that the viewer can visualize the relationship of health outcome and carbon emissions while concurrently comparing the prevalence of each result.

```{python}
#| fig-align: center

# Statewide emissions graph
ghgp_data_path = script_dir / 'data/raw-data/ghgp_data_2021.xlsx'
outcomes_data_path = script_dir / 'data/derived-data/outcomes.csv'


ghgp = pd.read_excel(ghgp_data_path)
outcomes = pd.read_csv(outcomes_data_path)

color_palette = [
    "#041556", # 
    "#748dc6", # 
    "#c3e8ff", # 
    "#601414", # 
    "#c48f8f"  # 
]

health_long = outcomes.melt(
    id_vars="County",
    value_vars=[
        "Asthma Incidence",
        "COPD Deaths",
        "COVID Deaths",
        "Heart Failures",
        "Stroke Deaths",
    ],
    var_name="Health Outcome",
    value_name="Rate"
)

#Data Cleaning

ghgp = ghgp.iloc[3:].reset_index(drop=True)

ghgp = ghgp[["Unnamed: 4", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Unnamed: 13"]]
ghgp.rename(columns={"Unnamed: 4": "State", "Unnamed: 7": "County", "Unnamed: 8": "Latitude", "Unnamed: 9": "Longitude", "Unnamed: 13": "Total Direct Emissions"}, inplace=True)

ghgp = ghgp[ghgp["State"] == "IL"]
ghgp = ghgp.dropna()

ghgp["County"] = (ghgp["County"]
                  .astype(str)
                  .str.strip()
                  .str.lower()
                  .str.replace(r"county.*$", "", regex=True)
                  .str.replace(r"\s+", " ", regex=True)
                  .str.strip()
                  .str.title()
)

ghgp = ghgp.groupby("County", as_index=False).agg({
    "Total Direct Emissions": "sum",
    "Latitude": "mean",
    "Longitude": "mean"
})

ghgp = ghgp[ghgp["County"] != "Lasalle"]

#Data Graphing

bar_chart = alt.Chart(health_long).mark_bar().encode(
    x=alt.X("County:N", title="Counties", sort=alt.SortField("Rate", order="descending")),
    y=alt.Y("Rate:Q", title="Death/Incidence Rates"),
    color=alt.Color("Health Outcome:N",
                    scale=alt.Scale(range=color_palette),
                    title="Health Outcome"),
    tooltip=["County", "Rate", "Health Outcome"]
).properties(
    width=400,
    height=200,
    title="Health Outcomes Rates by County from Most to Least (Top 20 Carbon Emitting in Illinois)"
)

bar_chart

```

Air pollutants are represented by the five most common pollutants: carbon monoxide (CO), nitrogen dioxide (NO2), Ozone, PM2.5, and PM10. This graph identifies patterns of pollutant levels and AQI measures of 20 randomly sampled Illinois counties, demonstrating how pollutants vary with air quality, depicting ozone has a pervasive contributor to AQI for counties with lower air quality indexes, and CO and NO2 being more prominent when AQI is high.

```{python}
#| fig-align: center
# AQI bar graph
data_path = script_dir / 'data/raw-data/daily_aqi_by_county_2025.csv'
aqi = pd.read_csv(data_path)

color_palette = [
    "#041556", # 
    "#748dc6", # 
    "#c3e8ff", # 
    "#601414", # 
    "#c48f8f"  # 
]

#Data Cleaning

aqi = aqi[["State Name", "county Name", "AQI", "Defining Parameter"]]
aqi.rename(columns={"State Name": "State", "county Name": "County"}, inplace=True)

aqi = aqi[aqi["State"] == "Illinois"]

aqi = aqi.groupby(["County", "Defining Parameter"], as_index=False).agg({"AQI": "mean"})

#Data Graphing

aqi_chart = alt.Chart(aqi).mark_bar().encode(
    x=alt.X("County:N", title="Counties in Illinois"),
    y=alt.Y("AQI:Q", title="Air Quality Index (AQI)"),
    color=alt.Color("Defining Parameter:N",
                    scale=alt.Scale(range=color_palette),
                    legend=alt.Legend(title="Defining Parameters")),
    tooltip=[
        alt.Tooltip("County:N"),
        alt.Tooltip("AQI:Q"),
        alt.Tooltip("Defining Parameter:N")
    ]
).properties(
    width=400,
    height=200,
    title="AQI of Illinois Counties by Defining Parameters"
).interactive()

aqi_chart
```

Incidence of the top 5 environmentally linked cancer types across counties in Illinois. This graph establishes the prevalence of some forms of cancer over others. Breast and lung and bronchus cancers show the highest prevalence in the state and are the two cancer forms with the most substantial medical research linking their development with pollution and carbon emissions. Due to data reporting requirements, it is not possible to report all cancer diagnoses in all counties, so looking at the statewide aggregate provides the best visualization for understanding variation among the prevalence of different types of environmentally linked cancers.

```{python}
#| fig-align: center
# Cancer incidence bar graph
data_path = script_dir / 'data/derived-data/combined_cancer_by_county.csv'
output_path = script_dir / 'data/derived-data/cancertype_bar.png'

df = pd.read_csv(data_path)

df["Cancer Type"] = (
    df["Cancer Type"]
        .str.replace("_", " ", regex=False)
        .str.replace("-bronch", "/Bronchus", regex=False)
        .str.replace(" Cancer", "", regex=False)
        .str.title())


base = alt.Chart(df).encode(
    x=alt.X('Cancer Type:N', sort=alt.SortField("Incidence", order='descending'), axis=alt.Axis(labelAngle=-45)),
    y='Incidence:Q'
)

background = base.mark_bar(
    color="#800000",
    opacity=1,
    stroke=None,
    size=40
)

foreground = base.mark_bar(
    color="#800000",
    opacity=1,
    stroke=None,
    size=40
)

chart = background + foreground
chart.properties(
    width=400, 
    height=200, 
    title='Cancer Incidence in Illinois by Type').show()
```

Rates of each of the 5 environmentally linked cancers by direct carbon emissions for the top 20 highest polluting counties in Illinois. The plot shows a faint trend across all combined types of cancer, but illustrates stronger relationships between emissions and the rates of the selected cancer types. Among the 5 cancer types, lung and bronchus cancer shows the strongest relationship with the weakest trend falling along the rates of bladder cancer and emissions. These findings tie back to our research question by examining environmentally related cancer rates in the highest carbon emitting counties in the state, which allows us to better establish a baseline trend for both cancer rates and levels of scope 1 and 2 emissions in these areas.

```{python}
#| fig-align: center
# Cancer-emissions scatterplot
output_path = script_dir / 'data/derived-data/emissions-cancer_scatter.png'

cancer_data_path = script_dir / 'data/derived-data/combined_cancer_by_county.csv'
cancer_df = pd.read_csv(cancer_data_path)

pop_data_path=script_dir / 'data/derived-data/population.csv'
pop_df = pd.read_csv(pop_data_path)

cancer_df["Cancer Type"] = (
    cancer_df["Cancer Type"]
        .str.replace("_", " ", regex=False)
        .str.replace("-bronch", "/Bronchus", regex=False)
        .str.replace(" Cancer", "", regex=False)
        .str.title())

cancer_rates_df = cancer_df.merge(pop_df, on='County', how="outer")
cancer_rates_df = cancer_rates_df.dropna()
cancer_rates_df["Incidence Rate"] = (cancer_rates_df["Incidence"] / cancer_rates_df["Population"]) * 100

ghgp_data_path = script_dir / 'data/derived-data/ghgp.csv'
emissions_df = pd.read_csv(ghgp_data_path)

ghgp_20 = emissions_df.sort_values(by="Total Direct Emissions", ascending=False).head(20).reset_index().copy()
top_20 = ghgp_20["County"].unique()

cancer_20 = cancer_rates_df[cancer_rates_df["County"].isin(top_20)].copy()

cancer_emissions_df = cancer_20.merge(ghgp_20, on='County', how="outer")
cancer_emissions_df["County"].nunique()

cancer_emissions_df.sort_values(by=["Incidence", "Total Direct Emissions"], ascending=False)

scatter = alt.Chart(cancer_emissions_df).mark_circle(filled=True, size=20).encode(
    y=alt.Y("Incidence Rate:Q", title="Cancer Incidence"),
    x=alt.X("Total Direct Emissions:Q", title="Total Direct Emissions"),
    color=alt.Color(
        "Cancer Type:N",
        title="Cancer Type",
        scale=alt.Scale(range=[
    "#EAAA00", "#275D38", "#007396",
    "#59315F", "#A4343A"]))
).properties(title="Cancer Incidence and Total Direct Emissions", width=250, height=200)
scatter
```

Indicates geographic concentrations of combined 5 cancer types and carbon emissions for each county in Illinois. The maps display some expected variation in both cancer incidence and emissions levels through population concentration and proximity to urban areas. Suppressed values on the maps represent values which are either concealed for data de-identification in reporting or for lack of emissions reporting in a particular county. These side by side visualizations help us better understand which counties in Illinois may be most affected by emissions-related negative health outcomes.

```{python}
#| fig-width: 2.7
#| fig-height: 1.62
#| fig-align: center
# Cancer and emissions small multiples choropleths 
output_path = script_dir / 'data/derived-data/county_map.png'

geo_data_path = script_dir / 'data/raw-data/Illinois_Counties.geojson'
il_gdf = gpd.read_file(geo_data_path)
il_gdf.head()

ghgp_data_path = script_dir / 'data/derived-data/ghgp.csv'
emissions_df = pd.read_csv(ghgp_data_path)

cancer_data_path = script_dir / 'data/derived-data/combined_cancer_by_county.csv'
cancer_df = pd.read_csv(cancer_data_path)
cancer_df['County'] = cancer_df['County'].str.lower()

cancer_gdf = il_gdf.merge(cancer_df, left_on="NAME_LC", right_on='County', how="left")

emissions_df['County'] = emissions_df['County'].str.lower()
cancer_emissions_gdf = cancer_gdf.merge(emissions_df, on='County', how="outer")


# Side by side comparison
fig, axes = plt.subplots(1, 2, figsize=(5.6, 3.5))

# Left: Cancer Incidence
inc_values = cancer_emissions_gdf["Incidence"].dropna()
bounds_left = np.unique(inc_values.quantile(np.linspace(0, 1, 6)))
if len(bounds_left) < 2:
    bounds_left = np.array([bounds_left[0], bounds_left[0] + 1])

cancer_emissions_gdf.boundary.plot(ax=axes[1], linewidth=0.2, edgecolor="black")
cancer_emissions_gdf.plot(
    ax=axes[0],
    column="Incidence",
    cmap="Blues",
    linewidth=0.2,
    edgecolor="black",
    scheme="quantiles",
    k=5,
    legend=False)

axes[0].set_title("Cancer Incidence", fontsize=9, loc="center")
axes[0].set_axis_off()

cbar_left = mcolorbar.ColorbarBase(
    axes[0].inset_axes([1.05, 0.1, 0.03, 0.8]),
    cmap=plt.cm.Blues,
    norm=mcolors.BoundaryNorm(bounds_left, plt.cm.Blues.N),
    orientation="vertical",
    ticks=np.round(bounds_left, 0),
    label="Incidence")
cbar_left.ax.tick_params(labelsize=7)  
cbar_left.ax.yaxis.label.set_size(8)
# Right: Total Direct Emissions
emissions_values = cancer_emissions_gdf["Total Direct Emissions"].dropna()
bounds_right = np.unique(emissions_values.quantile(np.linspace(0, 1, 6)))
if len(bounds_right) < 2:
    bounds_right = np.array([bounds_right[0], bounds_right[0] + 1])

cancer_emissions_gdf.boundary.plot(ax=axes[1], linewidth=0.2, edgecolor="black")
cancer_emissions_gdf.plot(
    ax=axes[1],
    column="Total Direct Emissions",
    cmap="Reds",
    linewidth=0.2,
    edgecolor="black",
    scheme="quantiles",
    k=5,
    legend=False)

axes[1].set_title("Total Direct Emissions", fontsize=9, loc='center')
axes[1].set_axis_off()

cbar_right = mcolorbar.ColorbarBase(
    axes[1].inset_axes([1.05, 0.1, 0.03, 0.8]),
    cmap=plt.cm.Reds,
    norm=mcolors.BoundaryNorm(bounds_right, plt.cm.Reds.N),
    orientation="vertical",
    ticks=np.round(bounds_right, 2),
    label="Total Direct Emissions")
cbar_right.ax.tick_params(labelsize=7)  
cbar_right.ax.yaxis.label.set_size(8)

cbar_right.ax.yaxis.set_major_formatter(ScalarFormatter())
cbar_right.ax.yaxis.get_major_formatter().set_scientific(False)
cbar_right.ax.yaxis.get_major_formatter().set_useOffset(False)
plt.savefig(output_path)
```

### Streamlit App
The dashboard displays two interactive graphs. The default graph shows five negative health outcomes, asthma incidence, COPD deaths, COVID deaths, stroke deaths, and heart failure, tied to carbon emissions across the top 20 highest polluting counties in Illinois. Users may select any of the 5 outcomes from the sidebar menu to look at their values individually, or can view the default visualization showing all 5 measures across the counties. The second graph that users can select from the sidebar shows the air quality index measurements bar graph. Users can hover over the bars to view the air quality index measurement, county name, and defining parameter for each bar shown. The dashboard visualizations hint at how increased tracking and reporting standards for carbon emissions as a result of the Corporate Climate Accountability Act may inform our understanding of the relationship between public health and carbon emissions in Illinois.
